// Generated by CoffeeScript 1.6.3
var appDep;

appDep = {
  components: {
    main: {
      url: 'main.js',
      loaded: false
    }
  },
  addComponent: function(component) {
    var c, s;
    c = this.components[component];
    if (c && c.loaded === false) {
      s = document.createElement('script');
      s.setAttribute('type', 'text/javascript');
      s.setAttribute('src', c.url);
      document.getElementsByTagName('head')[0].appendChild(s);
      c.loaded = true;
    }
  },
  componentAvailable: function(component) {
    this.component[component].loaded = true;
    if (this.listener) {
      this.listener(component);
    }
  }
};
